/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

// @generated by enums.py

package com.facebook.yoga

public enum class YogaExperimentalFeature(public val intValue: Int) {
  WEB_FLEX_BASIS(0);

  public fun intValue(): Int = intValue

  public companion object {
    @JvmStatic
    public fun fromInt(value: Int): YogaExperimentalFeature =
        when (value) {
          0 -> WEB_FLEX_BASIS
          else -> throw IllegalArgumentException("Unknown enum value: $value")
        }
  }
}
